server:
  port: 8080

logging.level.io.github.resilience4j: DEBUG

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: searchbarMicroservice
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/home
        - id: searchbarMicroserviceTest
            uri: http://test-sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
            predicates:
              - Path=/rest/searchbar/**
            filters:
              - name: CircuitBreaker
                args:
                  name: CircuitBreaker
                  fallbackUri: forward:/home
        - id: fallbackService
          uri: google.com
          predicates:
            - Path=/home

resilience4j.circuitbreaker:
  instances:
    CircuitBreaker:
      slidingWindowSize: 20
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.cloud.gateway.support.TimeoutException
        - org.springframework.web.server.ResponseStatusException
      registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

