server:
  port: 8080

logging.level.io.github.resilience4j: DEBUG

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: registration
            uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
            predicates:
              - Path=/rest/registration
            filters:
              - name: CircuitBreaker
                args:
                  name: CircuitBreaker
                  fallbackUri: forward:/fallbackNutriInput
        - id: login
            uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
            predicates:
              - Path=/rest/login
            filters:
              - name: CircuitBreaker
                args:
                  name: CircuitBreaker
                  fallbackUri: forward:/fallbackNutriInput
        - id: getMealById
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getMealByDate
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{day}/{month}/{year}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getAJoke
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/tellAJoke/{category}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: createMealWithDateAndCategory
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
              - Path=/rest/meal/{day}/{month}/{year}/{category}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: updateFoodQuantity
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}/{quantity}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: deleteAFoodFromMeal
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: addFoodToMeal
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}/{quantity}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getFoodById
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getFoodByName
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/name={name}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput


        - id: PostExcel
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getMineralsById
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/minerals/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getVitaminsById
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/vitamins/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getNutritionalValues
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/nutritionalValues/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: listNormal
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/{name}/{f}/{l}/{h}/{vegan}/{vegetarisch}/{mink}/{maxk}/{minp}/{maxp}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: saveRezept
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/addR/{name}/{az}/{kz}/{p}/{ma}/{iv}/{ivt}/{h}/{l}/{f}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: addFood
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/addF/{id}/{name}/{k}/{p}/{menge}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: deleteRezept
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/delete/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: deleteFoodFromRezept
          uri: http://sweng-sweng-team12-nutriapp-searchbar.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/searchbar/deleteF/{rId}/{fId}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: fallbackService
          uri: http://sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/fallbackNutriInput


resilience4j.circuitbreaker:
  instances:
    CircuitBreaker:
      slidingWindowSize: 20
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.cloud.gateway.support.TimeoutException
        - org.springframework.web.server.ResponseStatusException
      registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

