server:
  port: 8080

logging.level.io.github.resilience4j: DEBUG

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 500
        response-timeout: 500
      routes:
        - id: getMealById
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: createMealWithDateAndCategory
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{day}/{month}/{year}/{category}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: updateFoodQuantity
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}/{quantity}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: deleteAFoodFromMeal
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: addFoodToMeal
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/meal/{mealId}/{foodId}/{quantity}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getFoodById
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput
        - id: getFoodByName
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/name={name}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getFoodInfo
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/getInfo/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: PostExcel
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/food/
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getMineralsById
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/minerals/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getVitaminsById
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/vitamins/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: getNutritionalValues
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/rest/nutritionalValues/{id}
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/fallbackNutriInput

        - id: fallbackServiceNutriApp
          uri: http://test-sweng-sweng-team12-nutritionapp.wi-k8s.fh-muenster.de
          predicates:
            - Path=/fallbackNutriInput


resilience4j.circuitbreaker:
  instances:
    CircuitBreaker:
      slidingWindowSize: 20
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - org.springframework.cloud.gateway.support.TimeoutException
        - org.springframework.web.server.ResponseStatusException
      registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

